Repository fusionjs/fusion-plugin-rpc-redux-react, pull requests merged in 2018-10, with the labels that each got.

#141 Bump version of fusion-plugin-rpc-redux to v1.2.0
  package.json
  yarn.lock
Labels: bugfix

#142 Release v2.0.1
  package.json
Labels: release

#144 Upgrade dependency versions
  package.json
  src/__tests__/index.node.js
  yarn.lock
Labels: greenkeeping

#148 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
