Repository fusionjs/fusion-plugin-rpc-redux-react, pull requests merged in 2018-11, with the labels that each got.

#151 Fix types
  package.json
  src/__tests__/index.browser.js
  src/plugin.js
  yarn.lock
Labels: bugfix

#152 Release v2.0.2-0
  package.json
Labels: release

#154 Release v2.0.2
  package.json
Labels: release

#156 Upgrade dependencies
  package.json
  src/__tests__/index.browser.js
  yarn.lock
Labels: greenkeeping
