Repository fusionjs/fusion-plugin-rpc-redux-react, pull requests merged in 2019-01, with the labels that each got.

#160 Use Anonymous as a fallback for HoC naming
  src/hoc.js
Labels: bugfix, dependencies

#161 Release v2.0.3-0
  package.json
Labels: release

#164 Release v2.0.3-1
  package.json
Labels: release

#168 Add peerDependency on react-redux
  package.json
Labels: bugfix

#171 Release v2.0.4-0
  package.json
Labels: release

#172 Release v2.0.4
  package.json
Labels: release

#173 Upgrade flow-bin@latest and any packages raising Flow complaints
  package.json
  yarn.lock
Labels: bugfix
