Repository fusionjs/fusion-plugin-rpc-redux-react, pull requests merged in 2019-02, with the labels that each got.

#178 Release v2.0.5-0
  package.json
Labels: release

#180 Release v2.0.5
  package.json
Labels: release

#184 Upgrade fusion-rpc-redux and fix test regression
  package.json
  src/__tests__/index.browser.js
  yarn.lock
Labels: bugfix

#186 Release v2.0.6-0
  package.json
Labels: release

#189 Release v2.0.6
  package.json
Labels: release

#191 Fix flowtypes for mapStateToParams
  src/hoc.js
Labels: bugfix

#190 Pass own props to mapStateToProps
  src/__tests__/index.browser.js
  src/hoc.js
Labels: feature
