Repository fusionjs/fusion-plugin-rpc-redux-react, pull requests merged in 2019-03, with the labels that each got.

#192 Release v2.1.0-0
  package.json
Labels: release

#181 Import and export ActionType from dependency fusion-rpc-redux ^1.4.0
  src/index.js
Labels: greenkeeping

#194 Release v2.1.0
  package.json
Labels: release

#196 Update fusion-react peer dep
  package.json
Labels: greenkeeping

#195 Fix ownProps type signature
  src/hoc.js
Labels: bugfix

#197 Release v2.1.1
  package.json
Labels: release
